version: "3.8"

services:
  app:
    image: flask-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge