FROM ubuntu:22.04

RUN apt update && apt install -y \
    python3 \
    python3-venv \
    python3-pip \
    git \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN python3 -m venv /opt/venv 

ENV PATH="opt/venv/bin:$PATH"

ENV FLASK_APP=app.py

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]